### ISSUE TITLE
Managing pools/poolgroups in AVI

### ISSUE THREAD

**Issue by roddyrod74** [avinetworks/ansible-role-aviconfig#109]
Hi.  I have a question about managing pools and/or poolgroups in AVI.  I recently wrote and executed the following task below.  My intent was to disable an active pool in AVI.  It worked but it also did more than what I expected.  In addition to disabling the pool member, it also changed the configs for the pool member.  Am I using the right module and/or parameters?

tasks:
   - name: Disable pool member
     avi_pool:
        controller:
        username:
        password:
        tenant:
        api_version
        name:
        enabled:

Any information you can provide would be great.  Thanks.

**Comment by sabandi** [comment]
Hi @roddyrod74,

The module you are using is correct. Could you please give some more details on what unexpected changes did you observe.
Also, I am assuming the task contains more info along with name and enabled flag.

**Comment by roddyrod74** [comment]
Hi @sabandi,

Thanks for your reply.  The unexpected change was what you described above.  It removed the config for the pool I wanted to disable.  You mentioned sending a PUT request with the payload given in the task.  Is that how I would keep the existing config from being removed?

High-level, we have situations sometimes where he have to restart the server the pool is configured for.  So that we don't interrupt traffic, we usually disable the pool, restart the host, enable the pool after the server is up.

**Comment by sabandi** [comment]
Hi @roddyrod74,

So If I understand correctly, you want to disable an existing pool. We can do it in two ways.
Let's assume you created a pool using the below payload:
```
- name: Create pool
    avi_pool:
      avi_credentials: "{{ avi_credentials | default(omit)}}"
      name: my-pool
      servers:
      - ip:
            addr: "1.1.1.1"
           type: 'V4'
```
If you want to disable the pool, you can follow any of the below approaches

**Method 1:**
You need to copy the same payload and add `enabled:false` flag to it. This internally does a PUT call. So, it is important to have same payload as the actual pool.

```
- name: Disable  pool
    avi_pool:
      avi_credentials: "{{ avi_credentials | default(omit)}}"
      name: my-pool
      enabled: false
      servers:
      - ip:
           addr: "1.1.1.1"
           type: 'V4'
```

**Method 2:**

Use patch method. Here we can simply update specific fields without passing the whole payload.

```
    - name: Disable pool
      avi_pool:
        avi_credentials: "{{ avi_credentials | default(omit)}}"
        name: my-pool
        enabled: false
        avi_api_update_method: patch
        avi_api_patch_op: replace
```
